name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to display"
        required: true
      run_id:
        description: "Run id of triggering workflow"
        required: true
      artifact_id:
        description: "Artifact id"
        required: true

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Triggered Workflow
        run: |
          echo "This is the triggered workflow!"
          echo 'This is the message: "${{ inputs.message }}"'
          echo 'This is the triggering workflow id: "${{ inputs.run_id }}"'
          echo 'This is the artifact id: "${{ inputs.artifact_id }}"'
      - name: List Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: resume
          path: apps/resumes
          github-token: ${{ secrets.PAT }}
          run-id: ${{ inputs.run_id }}
          repository: isahohieku/repo-workflow-trigger
      - name: View downloaded Artifact in directoury
        run: |
          pwd
          cd apps/resumes
          ls
