name: Source Workflow

on:
  push:
    branches:
      - trigger

jobs:
  trigger-other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive an artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: resume
          path: dist/resume.pdf
          if-no-files-found: error
          retention-days: 1
      - name: Trigger Another Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          ARTIFACT_ID: ${{ steps.artifact-upload.outputs.artifact-id }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/isahohieku/repo-workflow-trigger/actions/workflows/triggered-workflow.yml/dispatches \
            -d '{"ref":"main", "inputs":{
              "message":"Hello from the source workflow!", 
              "artifact_id":"$ARTIFACT_ID", 
              "run_id":"$GITHUB_RUN_ID"}}'
